{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "asterscope.secretName" . }}
  labels:
    {{- include "asterscope.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "asterscope.secretName" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.remoteRefs }}
    - secretKey: {{ .property }}
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
    {{- end }}
{{- end }}
