{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asterscope.secretName" . }}
  labels:
    {{- include "asterscope.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
